# version: '3.8' # docker-compose version can be omitted now

# Define services (containers)
services:
  app:
    # Build context is the current directory where the Dockerfile is located
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Map host ports to the container
      - '80:3000'
      - '443:3000'
    environment:
      # Set environment variable for production mode
      - NODE_ENV=production
    # volumes:
    # Optional: Mount current directory to the container (for dev environments)
    # - .:/usr/src/app
    # Automatically restart the container if crashes, unless you stop it manually
    restart: unless-stopped
